from django.core.management.base import BaseCommand, CommandError
from django.utils import timezone
from pdf_generator.core.generator import PDFGenerator
import json

class Command(BaseCommand):
    help = 'Generate a PDF using the PDF Generator app'

    def add_arguments(self, parser):
        parser.add_argument(
            '--template',
            type=str,
            default='pdf_generator/default.html',
            help='Template to use for the PDF'
        )
        parser.add_argument(
            '--output',
            type=str,
            default='generated.pdf',
            help='Output filename for the PDF'
        )
        parser.add_argument(
            '--context',
            type=str,
            default='{}',
            help='JSON context data for the template'
        )
        parser.add_argument(
            '--options',
            type=str,
            default='{}',
            help='JSON options for PDF generation'
        )
        parser.add_argument(
            '--format',
            type=str,
            choices=['A4', 'A3', 'A5', 'Letter', 'Legal', 'Tabloid'],
            default='A4',
            help='Page format'
        )
        parser.add_argument(
            '--orientation',
            type=str,
            choices=['portrait', 'landscape'],
            default='portrait',
            help='Page orientation'
        )
        parser.add_argument(
            '--margins',
            type=str,
            default='{"top": "0.5in", "right": "0.5in", "bottom": "0.5in", "left": "0.5in"}',
            help='JSON margins configuration'
        )

    def handle(self, *args, **options):
        try:
            # Parse JSON arguments
            context = json.loads(options['context'])
            pdf_options = json.loads(options['options'])
            margins = json.loads(options['margins'])
            
            # Add default context if empty
            if not context:
                context = {
                    'title': 'Test Document',
                    'subtitle': 'Generated by PDF Generator',
                    'date': timezone.now().strftime('%B %d, %Y'),
                    'content': '<p>This is a test document generated by the PDF Generator app.</p>'
                }
            
            # Merge options
            pdf_options.update({
                'format': options['format'],
                'orientation': options['orientation'],
                'margins': margins,
                'filename': options['output']
            })
            
            self.stdout.write("Generating PDF with Playwright...")
            
            # Generate PDF
            pdf_bytes = PDFGenerator.generate_from_template(
                template_name=options['template'],
                context=context,
                options=pdf_options
            )
            
            # Save the PDF to a file
            file_path = PDFGenerator.save_to_file(
                pdf_bytes=pdf_bytes,
                filename=options['output']
            )
            
            self.stdout.write(
                self.style.SUCCESS(f"✅ PDF generated successfully!")
            )
            self.stdout.write(f"📄 File saved as: {file_path}")
            self.stdout.write(f"📊 File size: {len(pdf_bytes)} bytes")
            
            # Print context used
            self.stdout.write(f"📋 Context used: {json.dumps(context, indent=2)}")
            
        except json.JSONDecodeError as e:
            raise CommandError(f"Invalid JSON in arguments: {e}")
        except Exception as e:
            raise CommandError(f"Error generating PDF: {e}") 