# Generated by Django 5.2.3 on 2025-06-18 16:03

import django.db.models.deletion
import resume_builder.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=resume_builder.models.resume_pdf_path)),
                ('template_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_content', models.TextField(default='')),
                ('optimized_content', models.TextField(default='')),
                ('job_description', models.TextField(default='')),
                ('keyword_matches', models.JSONField(default=list)),
                ('improvement_suggestions', models.JSONField(default=list)),
                ('ats_score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
