# Generated by Django 5.2.3 on 2025-06-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0002_resume_additional_resume_draft_resume_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_optimized',
            field=models.BooleanField(default=False),
        ),
    ]
