# Generated by Django 5.2.3 on 2025-06-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0003_resume_is_optimized'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='relevant_experience',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
