# Generated by Django 5.2.3 on 2025-08-17 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for the AI service', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text="Used in code to identify this service (e.g., 'cover_letter', 'resume_optimization')", unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this AI service does')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Service',
                'verbose_name_plural': 'AI Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIPromptConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this prompt variant', max_length=100)),
                ('slug', models.SlugField(help_text="Used in code to identify this prompt variant (e.g., 'default', 'with_email_subject')")),
                ('system_prompt', models.TextField(help_text='The system prompt that will be sent to the AI')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this prompt is currently active')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default prompt for this service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(help_text='The AI service this prompt belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='ai_service.aiservice')),
            ],
            options={
                'verbose_name': 'AI Prompt Configuration',
                'verbose_name_plural': 'AI Prompt Configurations',
                'ordering': ['service', 'name'],
                'unique_together': {('service', 'slug')},
            },
        ),
    ]
