# Generated by Django 5.2.3 — ResumeJobEvaluation

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeJobEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_description", models.TextField()),
                ("resume_text", models.TextField()),
                (
                    "gemini_model",
                    models.CharField(
                        blank=True,
                        help_text="Gemini model id used for this run.",
                        max_length=128,
                    ),
                ),
                ("succeeded", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                (
                    "overall_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "optimization_potential",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("recommendation", models.CharField(blank=True, max_length=128)),
                (
                    "instruction_slug",
                    models.SlugField(
                        blank=True,
                        help_text="Snapshot of prompt_configuration.slug used for versioning.",
                        max_length=80,
                    ),
                ),
                ("evaluation_json", models.JSONField(blank=True, null=True)),
                ("raw_response_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prompt_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resume_job_evaluations",
                        to="ai_service.aipromptconfiguration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Resume-job evaluation",
                "verbose_name_plural": "Resume-job evaluations",
            },
        ),
    ]
