# Generated by Django 5.2.13 on 2026-05-18 20:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0002_resumejobevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='aipromptconfiguration',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sampling temperature for this prompt (0–2). Leave blank to use the model or env default.', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='resumejobevaluation',
            name='temperature_used',
            field=models.FloatField(blank=True, help_text='Temperature used for this run.', null=True),
        ),
        migrations.AlterField(
            model_name='resumejobevaluation',
            name='gemini_model',
            field=models.CharField(blank=True, help_text='Gemini model id used for this run (snapshot).', max_length=128),
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI')], default='gemini', max_length=32)),
                ('model_id', models.CharField(help_text='API model id (e.g. gemini-2.5-flash).', max_length=128)),
                ('display_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive models are hidden from admin dropdowns.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('default_temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Suggested default when a prompt does not set temperature.', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI model',
                'verbose_name_plural': 'AI models',
                'ordering': ['sort_order', 'display_name'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'model_id'), name='ai_service_aimodel_provider_model_id_uniq')],
            },
        ),
        migrations.AddField(
            model_name='aipromptconfiguration',
            name='ai_model',
            field=models.ForeignKey(blank=True, help_text='Default model for runs using this prompt variant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prompt_configurations', to='ai_service.aimodel'),
        ),
        migrations.AddField(
            model_name='resumejobevaluation',
            name='ai_model',
            field=models.ForeignKey(blank=True, help_text='Model catalog row used for this run.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_job_evaluations', to='ai_service.aimodel'),
        ),
    ]
