# Generated by Django 5.2.13 on 2026-05-22 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0005_job_fit_gate_and_evaluation_user'),
        ('dashboard', '0007_jobapplication_fit_review_status'),
        ('resume_builder', '0011_gallery_section_student_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyShouldIApplyPlayground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Short label for this run (e.g. “Acme PM role test”).', max_length=200)),
                ('description', models.TextField(blank=True, help_text='What you are testing—prompt version, resume variant, job source, etc.')),
                ('job_description', models.TextField()),
                ('resume_text', models.TextField()),
                ('gemini_model', models.CharField(blank=True, help_text='Gemini model id used for this run (snapshot).', max_length=128)),
                ('temperature_used', models.FloatField(blank=True, help_text='Temperature used for this run.', null=True)),
                ('succeeded', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('answer_text', models.TextField(blank=True, help_text='Generated application answer (plain text, no letter framing).')),
                ('instruction_slug', models.SlugField(blank=True, help_text='Snapshot of prompt_configuration.slug used for versioning.', max_length=80)),
                ('raw_response_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_model', models.ForeignKey(blank=True, help_text='Model catalog row used for this run.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='why_should_i_apply_playgrounds', to='ai_service.aimodel')),
                ('job_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='why_should_i_apply_playgrounds', to='dashboard.jobapplication')),
                ('prompt_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='why_should_i_apply_playgrounds', to='ai_service.aipromptconfiguration')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='why_should_i_apply_playgrounds', to='resume_builder.resume')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='why_should_i_apply_playgrounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Why should I apply playground',
                'verbose_name_plural': 'Why should I apply playground',
                'ordering': ['-created_at'],
            },
        ),
    ]
