# Generated by Django 5.2.13 on 2026-05-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_service", "0008_alter_aimodel_provider_deepseek"),
        ("resume_builder", "0011_gallery_section_student_templates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessionalSummaryPlayground",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Short label for this run (e.g. “Upload v2 summary test”).",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="What you are testing—prompt version, resume variant, model comparison, etc.",
                    ),
                ),
                (
                    "resume_text",
                    models.TextField(
                        help_text="Resume content as plain text or structured JSON paste for testing.",
                    ),
                ),
                (
                    "openai_model",
                    models.CharField(
                        blank=True,
                        help_text="OpenAI model id used for this run (snapshot).",
                        max_length=128,
                    ),
                ),
                (
                    "temperature_used",
                    models.FloatField(
                        blank=True,
                        help_text="Temperature used for this run.",
                        null=True,
                    ),
                ),
                ("succeeded", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                (
                    "summary_text",
                    models.TextField(
                        blank=True,
                        help_text="Generated professional summary.",
                    ),
                ),
                (
                    "instruction_slug",
                    models.SlugField(
                        blank=True,
                        help_text="Snapshot of prompt_configuration.slug used for versioning.",
                        max_length=80,
                    ),
                ),
                ("raw_response_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ai_model",
                    models.ForeignKey(
                        blank=True,
                        help_text="Model catalog row used for this run.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="professional_summary_playgrounds",
                        to="ai_service.aimodel",
                    ),
                ),
                (
                    "prompt_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="professional_summary_playgrounds",
                        to="ai_service.aipromptconfiguration",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="professional_summary_playgrounds",
                        to="resume_builder.resume",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_summary_playgrounds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Professional summary playground",
                "verbose_name_plural": "Professional summary playground",
                "ordering": ["-created_at"],
            },
        ),
    ]
