# Generated by Django 5.2.14 on 2026-07-30 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0011_resume_optimization_playground'),
        ('resume_builder', '0011_gallery_section_student_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeoptimizationplayground',
            name='instruction_slug',
            field=models.SlugField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='TitleFamilyPlayground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Short label for this run (e.g. “Backend eng — flash v1”).', max_length=200)),
                ('description', models.TextField(blank=True, help_text='What you are testing—prompt version, resume variant, model comparison, etc.')),
                ('resume_text', models.TextField(help_text='Resume content as plain text (or paste after loading a PDF).')),
                ('model_id_snapshot', models.CharField(blank=True, help_text='Provider model id used for this run (snapshot).', max_length=128)),
                ('temperature_used', models.FloatField(blank=True, help_text='Temperature used for this run.', null=True)),
                ('succeeded', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('primary_titles', models.JSONField(blank=True, default=list)),
                ('related_titles', models.JSONField(blank=True, default=list)),
                ('exclude_titles', models.JSONField(blank=True, default=list)),
                ('instruction_slug', models.SlugField(blank=True, help_text='Snapshot of prompt_configuration.slug used for versioning.', max_length=80)),
                ('raw_response_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_model', models.ForeignKey(blank=True, help_text='Model catalog row used for this run.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_family_playgrounds', to='ai_service.aimodel')),
                ('prompt_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_family_playgrounds', to='ai_service.aipromptconfiguration')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_family_playgrounds', to='resume_builder.resume')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_family_playgrounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Title family playground',
                'verbose_name_plural': 'Title family playground',
                'ordering': ['-created_at'],
            },
        ),
    ]
