# Generated by Django 5.2.13 on 2026-05-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_utility', '0005_deactivate_yahoo_smtp_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailhistory',
            name='attachment_type',
            field=models.CharField(choices=[('resume', 'Resume'), ('cover_letter', 'Cover Letter'), ('job_application', 'Job Application')], max_length=50),
        ),
    ]
