# Generated by Django 5.2.3 on 2025-06-22 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverletter', '0002_rename_created_at_coverletter_generated_at_and_more'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='cover_letter_link',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to='coverletter.coverletter'),
        ),
    ]
