# Generated by Django 5.2.3 on 2025-06-22 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_jobapplication_cover_letter_link_and_more'),
        ('resume_builder', '0003_resume_is_optimized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume_link',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to='resume_builder.resume'),
        ),
    ]
