# Generated by Django 5.2.3 on 2025-08-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_jobapplication_resume_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='email_subject',
            field=models.CharField(blank=True, help_text='AI-generated email subject line', max_length=200, null=True),
        ),
    ]
