# Generated by Django 5.2.13 on 2026-05-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_jobapplication_email_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='application_kind',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_description',
            field=models.TextField(blank=True, help_text='Full job posting text used for AI generation'),
        ),
    ]
