# Generated by Django 5.2.3 on 2025-06-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverletterinstruction',
            name='instructions',
        ),
        migrations.AddField(
            model_name='coverletterinstruction',
            name='closing',
            field=models.CharField(default='End with "Sincerely," followed by the applicant name on a new line', max_length=255),
        ),
        migrations.AddField(
            model_name='coverletterinstruction',
            name='enthusiasm',
            field=models.CharField(default='Show enthusiasm for the role and company', max_length=255),
        ),
        migrations.AddField(
            model_name='coverletterinstruction',
            name='examples',
            field=models.CharField(default='Include specific examples and achievements', max_length=255),
        ),
        migrations.AddField(
            model_name='coverletterinstruction',
            name='focus',
            field=models.CharField(default='Focus on relevant experiences', max_length=255),
        ),
        migrations.AddField(
            model_name='coverletterinstruction',
            name='greeting',
            field=models.CharField(default='Start with "Dear Hiring Manager,"', max_length=255),
        ),
        migrations.AddField(
            model_name='coverletterinstruction',
            name='length_limit',
            field=models.CharField(default='Keep the length to one page maximum.', max_length=255),
        ),
        migrations.AddField(
            model_name='coverletterinstruction',
            name='no_dates',
            field=models.CharField(default='Do not include any dates or addresses', max_length=255),
        ),
        migrations.AddField(
            model_name='coverletterinstruction',
            name='tone',
            field=models.CharField(default='Maintain a professional yet engaging tone', max_length=255),
        ),
        migrations.AddField(
            model_name='coverletterinstruction',
            name='understanding',
            field=models.CharField(default="Demonstrate clear understanding of the company's needs", max_length=255),
        ),
    ]
