# Generated by Django 5.2.3 on 2025-07-10 18:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_service', '0002_interviewprepsession_interviewquestion_and_more'),
        ('resume_builder', '0004_resume_relevant_experience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('job_title', models.CharField(max_length=200)),
                ('application_reason', models.CharField(choices=[('career_growth', 'Career Growth & Advancement'), ('better_compensation', 'Better Compensation & Benefits'), ('work_life_balance', 'Better Work-Life Balance'), ('relocation', 'Relocation to New City/Country'), ('travel_opportunity', 'Travel & Work Abroad'), ('industry_change', 'Change of Industry'), ('company_culture', 'Better Company Culture'), ('remote_work', 'Remote Work Opportunities'), ('other', 'Other')], max_length=50)),
                ('other_reason', models.TextField(blank=True)),
                ('uploaded_resume', models.FileField(blank=True, null=True, upload_to='job_applications/resumes/')),
                ('country', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('city_preference', models.CharField(choices=[('specific_city', 'Specific City'), ('nearby_cities', 'Nearby Cities (within 50 miles)'), ('any_city', 'Any City in State/Province'), ('remote_only', 'Remote Only'), ('hybrid', 'Hybrid (Some Office Time)')], max_length=20)),
                ('specific_city', models.CharField(blank=True, max_length=100)),
                ('distance_preference', models.CharField(choices=[('0-25', '0-25 miles'), ('25-50', '25-50 miles'), ('50-100', '50-100 miles'), ('100+', '100+ miles'), ('any', 'Any distance')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('both', 'Both')], max_length=10)),
                ('salary_expectations', models.CharField(choices=[('negotiable', 'Negotiable'), ('market_rate', 'Market Rate'), ('specific_range', 'Specific Range')], max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.CharField(choices=[('immediately', 'Immediately'), ('2_weeks', '2 Weeks'), ('1_month', '1 Month'), ('2_months', '2 Months'), ('3_months', '3 Months'), ('flexible', 'Flexible')], max_length=20)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('jobs_found', models.IntegerField(default=0)),
                ('applications_submitted', models.IntegerField(default=0)),
                ('interviews_scheduled', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_notes', models.TextField(blank=True)),
                ('ai_optimization_applied', models.BooleanField(default=False)),
                ('cover_letters_generated', models.IntegerField(default=0)),
                ('resume_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume_builder.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='job_service_user_id_aa6db1_idx'), models.Index(fields=['job_title'], name='job_service_job_tit_3428d3_idx'), models.Index(fields=['country', 'state_province'], name='job_service_country_4a0ffe_idx')],
            },
        ),
    ]
