# Generated by Django 5.2.3 on 2025-07-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_service', '0003_jobapplicationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationrequest',
            name='city',
            field=models.CharField(blank=True, help_text='User-entered city name', max_length=100),
        ),
        migrations.AddField(
            model_name='jobapplicationrequest',
            name='countries',
            field=models.JSONField(blank=True, default=list, help_text='List of selected countries and states', null=True),
        ),
        migrations.AddField(
            model_name='jobapplicationrequest',
            name='distance',
            field=models.IntegerField(blank=True, help_text='Distance preference in miles', null=True),
        ),
        migrations.AlterField(
            model_name='jobapplicationrequest',
            name='city_preference',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplicationrequest',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapplicationrequest',
            name='distance_preference',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplicationrequest',
            name='state_province',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
