# Generated by Django 5.2.3 on 2025-07-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_service', '0004_jobapplicationrequest_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationrequest',
            name='work_arrangements',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred work arrangements (remote, hybrid, onsite)', null=True),
        ),
    ]
