# Generated by Django 5.2.14 on 2026-08-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_service', '0006_job_scraper_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='work_arrangement',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('unknown', 'Unknown')], db_index=True, default='unknown', help_text='Workplace mode inferred at scrape time (remote / hybrid / onsite).', max_length=20),
        ),
    ]
