# Generated by Django 5.2.13 on 2026-05-11 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_answer', '0003_interviewassistant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Interview category / profession', 'verbose_name_plural': 'Interview categories / professions'},
        ),
    ]
