# Generated by Django 5.2.3 on 2025-08-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_usersubscription_invoice_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='current_period_end',
            field=models.DateTimeField(blank=True, help_text='End of current billing period', null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='current_period_start',
            field=models.DateTimeField(blank=True, help_text='Start of current billing period', null=True),
        ),
    ]
