# Generated by Django 5.2.13 on 2026-05-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_planduration_price_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planduration',
            name='duration_type',
            field=models.CharField(choices=[('ONE_TIME', 'One Time'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SEMI_ANNUAL', 'Semi-Annual'), ('YEARLY', 'Yearly')], max_length=20),
        ),
    ]
