"""
PDF Generator Views

Optional web interface for the PDF Generator app.
"""

from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
from django.utils.decorators import method_decorator
from django.views import View
import json
import logging

from .core.generator import PDFGenerator

logger = logging.getLogger(__name__)

def index(request):
    """Simple index page for the PDF Generator app."""
    return render(request, 'pdf_generator/index.html', {
        'title': 'PDF Generator',
        'description': 'Generate high-quality PDFs using Playwright'
    })

@csrf_exempt
@require_http_methods(["POST"])
def generate_pdf_api(request):
    """
    API endpoint for generating PDFs.
    
    Expected JSON payload:
    {
        "template": "template_name.html",
        "context": {"key": "value"},
        "options": {"format": "A4", "orientation": "portrait"}
    }
    """
    try:
        data = json.loads(request.body)
        
        template = data.get('template', 'pdf_generator/default.html')
        context = data.get('context', {})
        options = data.get('options', {})
        
        # Generate PDF
        pdf_bytes = PDFGenerator.generate_from_template(
            template_name=template,
            context=context,
            options=options
        )
        
        # Return PDF as response
        response = HttpResponse(pdf_bytes, content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="generated.pdf"'
        return response
        
    except json.JSONDecodeError:
        return JsonResponse({'error': 'Invalid JSON'}, status=400)
    except Exception as e:
        logger.error(f"PDF generation error: {e}")
        return JsonResponse({'error': str(e)}, status=500)

@method_decorator(csrf_exempt, name='dispatch')
class PDFGeneratorView(View):
    """Class-based view for PDF generation."""
    
    def post(self, request, *args, **kwargs):
        """Handle POST requests for PDF generation."""
        try:
            data = json.loads(request.body)
            
            template = data.get('template', 'pdf_generator/default.html')
            context = data.get('context', {})
            options = data.get('options', {})
            
            # Generate PDF
            pdf_bytes = PDFGenerator.generate_from_template(
                template_name=template,
                context=context,
                options=options
            )
            
            # Return PDF as response
            response = HttpResponse(pdf_bytes, content_type='application/pdf')
            response['Content-Disposition'] = 'attachment; filename="generated.pdf"'
            return response
            
        except json.JSONDecodeError:
            return JsonResponse({'error': 'Invalid JSON'}, status=400)
        except Exception as e:
            logger.error(f"PDF generation error: {e}")
            return JsonResponse({'error': str(e)}, status=500)
    
    def get(self, request, *args, **kwargs):
        """Handle GET requests - show form."""
        return render(request, 'pdf_generator/form.html', {
            'title': 'PDF Generator Form'
        })

def test_pdf(request):
    """Test endpoint that generates a sample PDF."""
    try:
        context = {
            'title': 'Test PDF Document',
            'subtitle': 'Generated by PDF Generator App',
            'date': '2024-01-01',
            'content': '''
                <h2>Sample Content</h2>
                <p>This is a test PDF generated by the PDF Generator app.</p>
                <ul>
                    <li>Feature 1: High-quality rendering</li>
                    <li>Feature 2: CSS support</li>
                    <li>Feature 3: Template system</li>
                </ul>
            '''
        }
        
        pdf_bytes = PDFGenerator.generate_from_template(
            template_name='pdf_generator/default.html',
            context=context,
            options={'format': 'A4', 'print_background': True}
        )
        
        response = HttpResponse(pdf_bytes, content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="test_document.pdf"'
        return response
        
    except Exception as e:
        logger.error(f"Test PDF generation error: {e}")
        return JsonResponse({'error': str(e)}, status=500) 