# Generated by Django 5.2.14 on 2026-07-30 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume_builder', '0011_gallery_section_student_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimateAutomationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_titles', models.JSONField(blank=True, default=list, help_text='Core target roles, e.g. ["Backend Engineer", "Software Engineer"]')),
                ('related_titles', models.JSONField(blank=True, default=list, help_text='Adjacent synonyms / related roles for Stage 2 soft match')),
                ('exclude_titles', models.JSONField(blank=True, default=list, help_text='Roles to never match, e.g. ["Data Scientist", "Engineering Manager"]')),
                ('auto_apply_enabled', models.BooleanField(default=False, help_text='User must confirm title family before enabling')),
                ('title_family_confirmed', models.BooleanField(default=False)),
                ('title_family_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('max_applications_per_day', models.PositiveIntegerField(default=10)),
                ('setup_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ultimate_automation_profiles', to='resume_builder.resume')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ultimate_automation_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ultimate automation profile',
                'verbose_name_plural': 'Ultimate automation profiles',
            },
        ),
    ]
