# Generated by Django 5.2.14 on 2026-08-02 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_automation_search_preferences'),
        ('job_service', '0006_job_scraper_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_url', models.URLField(help_text='Snapshot of job.application_url at match time', max_length=500)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('applied', 'Applied'), ('skipped', 'Skipped')], db_index=True, default='queued', max_length=20)),
                ('skip_reason', models.CharField(blank=True, choices=[('captcha', 'CAPTCHA'), ('login_required', 'Login required'), ('job_closed', 'Job closed'), ('geo_block', 'Geo blocked'), ('email_only', 'Email-only apply'), ('other', 'Other')], max_length=50)),
                ('operator_notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_tasks', to='job_service.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apply task',
                'verbose_name_plural': 'Apply tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='automation__status_2cf472_idx'), models.Index(fields=['user', 'status', 'created_at'], name='automation__user_id_c7a3c2_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'job'), name='unique_apply_task_user_job')],
            },
        ),
    ]
