# Generated by Django 5.2.3 on 2025-06-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coverletter',
            old_name='created_at',
            new_name='generated_at',
        ),
        migrations.AddField(
            model_name='coverletter',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='processing_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='title',
            field=models.CharField(default='Cover Letter', max_length=200),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
