# Generated by Django 5.2.3 on 2025-06-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverletter', '0002_rename_created_at_coverletter_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
